version: '3'

services:
  apps:
    image: laravel_app_prod:1.0
    restart: always
    env_file:
      - prod.env
    depends_on:
      - pgsql
      - redis
    deploy:
      resources:
        limits:
          memory: 512M

  queue:
    image: laravel_app_prod:1.0
    restart: always
    env_file:
      - prod.env
    command:
      - php
      - artisan
      - queue:work
    depends_on:
      - pgsql
      - redis
    deploy:
      resources:
        limits:
          memory: 128M

  caddy:
    image: laravel_app_prod:1.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command:
      - /app/caddy
      - run
      - --config
      - /app/Caddyfile
    depends_on:
      - apps
    deploy:
      resources:
        limits:
          memory: 128M

  pgsql:
    image: postgres:16.1-alpine
    restart: always
    env_file:
      - prod.env
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7.2-alpine
    restart: always
    command:
      - redis-server
      - --appendonly
      - yes
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 64M

volumes:
  pgsql_data:
  redis_data:
